name = "glascontainer-magdeburg"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./dist/glascontainer-magdeburg",entry-point = "workers-site"}
compatibility_date = "2021-10-19"
account_id='7e2b90214b54908925e00ef2f9f6465d'