name: App Deploy

on:
  push:
    branches:
      - prod
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: | 
          npm ci
          npm run build:static

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiKey: ${{ secrets.API_KEY }}
          email: ${{ secrets.EMAIL }}
          environment: ${{ steps.extract_branch.outputs.branch }}
